[tool.black]
line-length = 120

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pylint]
disable = """
    attribute-defined-outside-init
"""
max-line-length = 120
max-args =  10
no-docstring-rgx = "test_*|Test*"
