name: Devcontainer build

on:
  pull_request:
    branches:
      - '*'

jobs:
  Build-devcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create empty ssh dir
        run: mkdir -p ~/.ssh
      - name: Create dummy bash_aliases
        run: touch ~/.bash_aliases
      - name: Create Decontainer
        uses: devcontainers/ci@v0.3
        with:
            runCmd: /usr/bin/echo Success
